"""
Output formatters for reports.

Supports JSON and text output formats.
"""

import json
from typing import Any


def format_report_json(
    analysis_results: dict[str, Any],
    recommendations: list[dict[str, Any]],
    overall_health: str,
    indent: int = 2,
) -> str:
    """
    Format analysis results as JSON.

    Args:
        analysis_results: Results from MetricsAnalyzer.analyze().
        recommendations: List of recommendation dictionaries.
        overall_health: Overall health status string.
        indent: JSON indentation level.

    Returns:
        JSON string.
    """
    high_priority_count = sum(1 for r in recommendations if r["priority"] == "HIGH")

    report = {
        "summary": {
            "industry": analysis_results["industry"],
            "metrics_analyzed": analysis_results["metrics_analyzed"],
            "metrics_with_benchmarks": analysis_results["metrics_with_benchmarks"],
            "high_priority_gaps": high_priority_count,
            "overall_health": overall_health,
        },
        "recommendations": recommendations,
        "detailed_analysis": analysis_results["analysis"],
        "metrics_without_benchmarks": analysis_results.get(
            "metrics_without_benchmarks", []
        ),
    }

    return json.dumps(report, indent=indent)


def format_report_text(
    analysis_results: dict[str, Any],
    recommendations: list[dict[str, Any]],
    overall_health: str,
) -> str:
    """
    Format analysis results as human-readable text.

    Args:
        analysis_results: Results from MetricsAnalyzer.analyze().
        recommendations: List of recommendation dictionaries.
        overall_health: Overall health status string.

    Returns:
        Formatted text string.
    """
    lines = []

    # Header
    lines.append("=" * 60)
    lines.append("GOOD AI METRICS ANALYSIS REPORT")
    lines.append("=" * 60)
    lines.append("")

    # Summary
    lines.append("SUMMARY")
    lines.append("-" * 40)
    lines.append(f"Industry:              {analysis_results['industry']}")
    lines.append(f"Metrics Analyzed:      {analysis_results['metrics_analyzed']}")
    lines.append(
        f"With Benchmarks:       {analysis_results['metrics_with_benchmarks']}"
    )

    high_count = sum(1 for r in recommendations if r["priority"] == "HIGH")
    lines.append(f"High Priority Gaps:    {high_count}")
    lines.append(f"Overall Health:        {overall_health}")
    lines.append("")

    # Recommendations
    if recommendations:
        lines.append("RECOMMENDATIONS")
        lines.append("-" * 40)

        for i, rec in enumerate(recommendations, 1):
            priority_indicator = _get_priority_indicator(rec["priority"])
            lines.append(f"\n{i}. [{priority_indicator}] {rec['metric']}")
            lines.append(
                f"   Current: {rec['current_value']} | Benchmark: {rec['benchmark_p50']}"
            )
            lines.append(f"   Gap: {rec['gap_percent']:.1f}% | Effort: {rec['effort']}")
            lines.append(f"   > {rec['recommendation']}")

        lines.append("")

    # Metrics without benchmarks
    without_benchmarks = analysis_results.get("metrics_without_benchmarks", [])
    if without_benchmarks:
        lines.append("METRICS WITHOUT BENCHMARKS")
        lines.append("-" * 40)
        for metric in without_benchmarks:
            lines.append(f"  - {metric}")
        lines.append("")

    lines.append("=" * 60)
    lines.append("Report generated by Good AI Metrics CLI")
    lines.append("Evidence over opinions. Leverage, not lore.")
    lines.append("=" * 60)

    return "\n".join(lines)


def _get_priority_indicator(priority: str) -> str:
    """Get a visual indicator for priority level."""
    indicators = {"HIGH": "!!", "MEDIUM": "! ", "LOW": "  "}
    return indicators.get(priority, "  ")


def format_health_check(health_result: dict[str, Any]) -> str:
    """
    Format health check results for CI/CD output.

    Args:
        health_result: Result from check_health_thresholds().

    Returns:
        Formatted text string.
    """
    lines = []

    if health_result["passed"]:
        lines.append("HEALTH CHECK: PASSED")
        lines.append(f"Metrics checked: {health_result['metrics_checked']}")
    else:
        lines.append("HEALTH CHECK: FAILED")
        lines.append(f"Metrics checked: {health_result['metrics_checked']}")
        lines.append("")
        lines.append("Failures:")

        for failure in health_result["failures"]:
            lines.append(f"  - {failure['check']}")
            lines.append(f"    Expected: {failure['expected']}")
            lines.append(f"    Actual: {failure['actual']}")

    return "\n".join(lines)


def format_comparison_json(comparison_results: dict[str, Any], indent: int = 2) -> str:
    """
    Format comparison results as JSON.

    Args:
        comparison_results: Results from compare_metrics().
        indent: JSON indentation level.

    Returns:
        JSON string.
    """
    return json.dumps(comparison_results, indent=indent)


def format_comparison_text(comparison_results: dict[str, Any]) -> str:
    """
    Format comparison results as human-readable text.

    Args:
        comparison_results: Results from compare_metrics().

    Returns:
        Formatted text string.
    """
    lines = []

    # Header
    lines.append("=" * 60)
    lines.append("GOOD AI METRICS COMPARISON REPORT")
    lines.append("=" * 60)
    lines.append("")

    # Summary
    summary = comparison_results["summary"]
    lines.append("SUMMARY")
    lines.append("-" * 40)
    lines.append(f"Industry:    {comparison_results['industry']}")
    lines.append(f"Compared:    {comparison_results['metrics_compared']} metrics")
    lines.append(f"Improved:    {summary['improved']}")
    lines.append(f"Declined:    {summary['declined']}")
    lines.append(f"Unchanged:   {summary['unchanged']}")
    lines.append("")

    # Comparisons
    if comparison_results["comparisons"]:
        lines.append("METRIC CHANGES")
        lines.append("-" * 40)

        for comp in comparison_results["comparisons"]:
            direction_symbol = _get_direction_symbol(
                comp["direction"], comp["improved"]
            )
            lines.append(
                f"{direction_symbol} {comp['metric']}: "
                f"{comp['before_value']} -> {comp['after_value']} "
                f"({comp['change_percent']:+.1f}%)"
            )

        lines.append("")

    # Metrics only in one file
    if comparison_results["only_in_before"]:
        lines.append("Only in BEFORE file:")
        for m in comparison_results["only_in_before"]:
            lines.append(f"  - {m}")
        lines.append("")

    if comparison_results["only_in_after"]:
        lines.append("Only in AFTER file:")
        for m in comparison_results["only_in_after"]:
            lines.append(f"  - {m}")
        lines.append("")

    lines.append("=" * 60)

    return "\n".join(lines)


def _get_direction_symbol(direction: str, improved: bool) -> str:
    """Get a symbol indicating change direction and improvement."""
    if direction == "unchanged":
        return "="
    elif improved:
        return "+"
    else:
        return "-"
